### PR TITLE
Changes required for hardware/software integration

### PR DESCRIPTION
**Pull request by shaun-edwards**
This PR contains many changes, but supports a fully functioning system (real and simulated).  These changes should be reviewed and back ported into the main `indigo-devel` branch.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Would it be an idea to do some selective squashing here and there? This could remove a lot of the 'tweaked X to Y' commits fi. Unless those commits are important for the history of the repository, of course.

**Comment by shaun-edwards** [comment]
In this case the history is important because we were improving the vehicle performance in some way.  It's helpful to know the past values of parameters, so that we know what has been tried.

**Comment by jrgnicho** [comment]
@shaun-edwards can this be closed?

**Comment by shaun-edwards** [comment]
These changes all look important and critical to a functioning system.  Assuming the Euler platform still works, I would guess these changes were merged elsewhere.  In other words, go ahead and close.

**Comment by jrgnicho** [comment]
We have a functional system at the moment so I think all the critical changes have been captured from other PRs.  Thanks

**Pull request closed without merging**
