### PR TITLE
Euler support virtual launch files

### PR DESCRIPTION
**Pull request by jrgnicho**
This PR addresses the following:
- Added launch files under euler_support to run simulation components
- Added launch file for bringing up the localization device

### CODE REVIEW

**Comment by DLu** [comment]
Would it make more sense to split stage.launch into two launch files and then include them here instead of replicating their contents?

**Comment by jrgnicho** [comment]
@DLu  that's a good point, I'll split up state.launch

**Comment by jrgnicho** [comment]
The last commit should address @DLu 's comment

**Comment by shaun-edwards** [comment]
+1.

**Pull request merged**
